### ISSUE TITLE
[Version] La version est 2.

### ISSUE THREAD

**Issue by jujudusud** [linuxmao-org/Mx44#4]
La version du code original devrait être réglée sur la valeur 2.
C'est la version diffusée par l'auteur du code déposé ici.

**Comment by jujudusud** [comment]
@ycollet est-ce qu'on peut passer à la bonne version ?

**Comment by ycollet** [comment]
Yes, let's go !

**Comment by jujudusud** [comment]
Je n'ai pas la main pour le faire sur ce projet.
Du coup je pense qu'il faut que ce soit toi qui le fasse ;-)

**Comment by ycollet** [comment]
Je vais regarder ça.
Où est-ce qu'il faut changer la version ? Je vois du Mx44.2 à peu près partout. Le tag est présent aussi ...

**Comment by jujudusud** [comment]
Ce n'est pas dans le code mais dans le dépôt.
Je m'occuperai du code ensuite.
https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#:~:text=GitHub%20CLI%20documentation.-,Creating%20a%20release,version%20number%20for%20your%20release.
C'est pour repartir depuis la bonne version d'insertion du code. Ensuite on attaquera les modifications et les montées de versions grâce aux tag dans git.

**Comment by ycollet** [comment]
Bon, je vois une Mx44.3 (le tag est présent dans le dépôt).
Je vois qu'il y a des releases Mx44.2 et Mx44.3 dans l'onglet release, mais je ne peux pas aller plus loin.
Je pense que je n'ai pas les droits non plus.

**Comment by jujudusud** [comment]
Les versions existantes sont :
- v0.44.2,
- v0.44.3.

Ces versions ne correspondent à rien ...
La version actuelle du code est : 
- v2.0.0

Peut être que tu n'as pas accès non plus.
Je vais essayer quand j'ai deux minutes avec les tag de git.

**Comment by ycollet** [comment]
Ah, je vois. Tu veux que je pousse le tag v2.0.
C'est ça ?
Ca, je peux le faire. J'attends juste ta confirmation et je le fais ASAP.

**Comment by jujudusud** [comment]
Euh oui,
Je pense qu'on peut même faire 
v2.0.0
comme ça, c'est tranquille pour les petites modifications, les moyennes et les changement de versions... :-)

**Comment by ycollet** [comment]
Bon, je viens de tenter de créer le tag, mais pas possible de le pusher:
$ git tag v2.0.0
$ git push --tags -> erreur  ...

**Comment by jpcima** [comment]
Je confirme qu'il faut pousser une étiquette.
En principe un `git push origin v2.0.0` fait l'affaire.

**Comment by jujudusud** [comment]
Ok, c'est fait grace à jp ! :-)
